In [2]:
import numpy as np

# Part 1: NumPy Practical Lab

## Task 1.1: Environmental Sensor Analytics

In [3]:
# A sensor records hourly temperatures over 72 hours. 
# Some readings are corrupted and contain unrealistic values.

np.random.seed(42)

raw_temperatures = np.random.normal(loc=24.0, scale=3.0, size=72)

# Simulated corrupt readings
raw_temperatures[[5, 12, 28, 45, 60]] = [99.9, -15.0, 88.8, -50.0, 102.4]

In [17]:
raw_temperatures

array([ 23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  99.9       ,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
       -15.        ,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        88.8       ,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515, -50.        ,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
       102.4       ,  23.65305515,  23.65305515,  23.65

In [4]:
# 1. Create a boolean mask for valid temperatures.
#    Valid range:
#    15.0 ≤ Temperature ≤ 40.0


valid_mask = (raw_temperatures >= 15) & (raw_temperatures <=40)
valid_temp = raw_temperatures[valid_mask]

In [5]:
valid_temp

array([25.49014246, 23.5852071 , 25.94306561, 28.56908957, 23.29753988,
       28.73763845, 26.30230419, 22.59157684, 25.62768013, 22.60974692,
       22.60281074, 18.26015927, 18.8252465 , 22.31313741, 20.96150664,
       24.942742  , 21.27592777, 19.7630889 , 28.39694631, 23.3226711 ,
       24.20258461, 19.72575544, 22.36685183, 24.33276777, 20.54701927,
       25.12709406, 23.12491875, 22.19488016, 29.55683455, 23.95950833,
       20.82686721, 26.46763474, 20.33746905, 24.62659079, 18.12098963,
       20.01544185, 24.59058371, 26.21539974, 24.51410484, 23.65305515,
       23.09668891, 19.56443403, 22.61808369, 27.17136668, 25.03085487,
       18.71087953, 24.97225191, 22.84475316, 21.969234  , 25.83502887,
       27.09299857, 26.79384036, 21.48234743, 23.07236287, 24.99379029,
       26.92663538, 23.44302307, 20.68099508, 20.41138013, 26.43757747,
       28.06872009, 23.78396964, 27.01059869, 25.08490808, 22.06464074,
       25.08418682, 28.6141097 ])

In [16]:
# 1.1.2 Replace all invalid values with the median of the valid temperatures.

valid_temp_median = np.median(raw_temperatures[valid_mask])
print(f"Median of the valid temperatures: {valid_temp_median:.2f}")

raw_temperatures[valid_mask] = valid_temp_median
raw_temperatures

Median of the valid temperatures: 23.65


array([ 23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  99.9       ,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
       -15.        ,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        88.8       ,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515, -50.        ,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
        23.65305515,  23.65305515,  23.65305515,  23.65305515,
       102.4       ,  23.65305515,  23.65305515,  23.65

In [7]:
# 1.1.3 Calculate and print:
#             Mean
#             Standard Deviation
#             Variance

## Without masking
print("Without Masking:")
unmasked_mean_temp = np.mean(raw_temperatures)
print(f"\tMean Temperature: {unmasked_mean_temp:.2f}")

unmasked_std_temp = np.std(raw_temperatures)
print(f"\tTemperature Standard Deviation: {unmasked_std_temp:.2f}")

unmasked_variance_temp = np.var(raw_temperatures)
print(f"\tTemperature Variance: {unmasked_variance_temp:.2f}")


## With masking
print("With Masking:")
masked_mean_temp = np.mean(raw_temperatures[valid_mask])
print(f"\tMean Temperature: {masked_mean_temp:.2f}")

masked_std_temp = np.std(raw_temperatures[valid_mask])
print(f"\tTemperature Standard Deviation: {masked_std_temp:.2f}")

masked_variance_temp = np.var(raw_temperatures[valid_mask])
print(f"\tTemperature Variance: {masked_variance_temp:.2f}")

Without Masking:
	Mean Temperature: 25.15
	Temperature Standard Deviation: 17.88
	Temperature Variance: 319.67
With Masking:
	Mean Temperature: 23.65
	Temperature Standard Deviation: 0.00
	Temperature Variance: 0.00


## Task 1.2: Matrix Slicing & Strided Operations

In [8]:
grid = np.arange(10, 74).reshape(8, 8)
grid

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73]])

In [9]:
# 1.2.1 Extract the center 4 × 4 portion of the matrix.
grid[2:6,2:6]

array([[28, 29, 30, 31],
       [36, 37, 38, 39],
       [44, 45, 46, 47],
       [52, 53, 54, 55]])

In [10]:
# 1.2.2 Extract the last column using a single slicing statement.
grid[:,-1]

array([17, 25, 33, 41, 49, 57, 65, 73])

In [11]:
# 1.2.3 Create a 4 × 4 downsampled matrix by selecting every second row and every second column.
grid[::2,::2]

array([[10, 12, 14, 16],
       [26, 28, 30, 32],
       [42, 44, 46, 48],
       [58, 60, 62, 64]])

# Part 2: Sliding Median Filter

In [12]:
# A noisy signal contains random spikes.
signal = np.array([10, 11, 99, 12, 13, -45, 14, 15, 16])

In [13]:
filtered_signal = signal.copy()

In [14]:
filtered_signal

array([ 10,  11,  99,  12,  13, -45,  14,  15,  16])

In [15]:
for i in range(1, 8):
    window = signal[i-1 : i+2]
    filtered_signal[i] = np.median(window)
    
print("Original signal:", signal)
print("Filtered signal:", filtered_signal)


Original signal: [ 10  11  99  12  13 -45  14  15  16]
Filtered signal: [10 11 12 13 12 13 14 15 16]


### Sliding Median Filter Explanation

Step-by-Step Array Updates
* **Loop 1 (`i=1`):** Window is `[10, 11, 99]`. Median is **11**. 
  * Array: `[10, 11, 99, 12, 13, -45, 14, 15, 16]` *(No change)*
* **Loop 2 (`i=2`):** Window is `[11, 99, 12]`. Median is **12**. 
  * Array: `[10, 11, 12, 12, 13, -45, 14, 15, 16]` *(99 is removed)*
* **Loop 3 (`i=3`):** Window is `[99, 12, 13]`. Median is **13**. 
  * Array: `[10, 11, 12, 13, 13, -45, 14, 15, 16]`
* **Loop 4 (`i=4`):** Window is `[12, 13, -45]`. Median is **13**. 
  * Array: `[10, 11, 12, 13, 13, -45, 14, 15, 16]`
* **Loop 5 (`i=5`):** Window is `[13, -45, 14]`. Median is **14**. 
  * Array: `[10, 11, 12, 13, 13, 14, 14, 15, 16]` *(-45 is removed)*

---
The median filter performs significantly better than a mean (average) filter because it completely ignores the actual size of extreme spikes (outliers).