In [1]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr.shape)
print(arr.ndim)

(2, 2)
2


In [2]:
# zeros/ones
np.zeros((2,3))
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
# Range Methods
np.arange(0,10,2)       # arange(start,stop, step)
np.linspace(0,1,5)      # linspace(start, end, count)
np.linspace(0,1,4)
np.arange(0,1,.33333)

array([0.     , 0.33333, 0.66666, 0.99999])

In [4]:
# Random
np.random.rand(3,2)   # for matrix
# np.random.randn(5) # for 1d array

array([[0.59403383, 0.23132782],
       [0.14962079, 0.47264626],
       [0.53556886, 0.39607671]])

In [5]:
a = np.arange(10)
# Reverse the array
a[::-1]

# Every 2nd element
a[::2]

# Middle Segment
a[2:7]

array([2, 3, 4, 5, 6])

In [6]:
matrix = np.random.randn(10,10)
print("matrix:", matrix)

# row_zero = matrix[0,:]
# print("\n\nrow_zero",row_zero)

# col_five = matrix[:,5]
# print("\n\ncol_five",col_five)

# top_corner = matrix[0:3,0:3]
# print("\n\n top_corner",top_corner)

bottom_row = matrix[-1,:]
print("\n\n bottom_row",bottom_row)

bottom_corner = matrix[-3:,-3:]
print("\n\n bottom_row", bottom_corner)

matrix: [[ 1.16963147 -0.83558207 -0.34430262 -1.46886413 -0.43977127  0.6742738
  -1.37030547  1.56985068 -1.39991836  1.0282482 ]
 [-1.46530224  0.20870945 -0.98825204  0.25957386 -0.24106037 -0.96018254
  -0.70747307 -1.51341775  0.09068667  1.14558112]
 [ 0.14908135  0.13064259 -0.0340544  -0.09107446  1.63306496 -0.25936978
   2.02195706  0.58614108  0.23462574 -0.7803516 ]
 [-1.21074262  1.57376883  1.28237113 -0.51083838  0.01347742  1.0644895
  -0.9023954   1.88546983  0.71565322  0.68721142]
 [ 0.9488242   2.82930858  0.01107769 -0.14642551  0.21576206 -1.25572831
   0.76387952  0.33126688 -2.19576013 -2.37460181]
 [-0.20715116  0.98787623  0.03583347 -0.18660536  1.68489889 -1.08463144
  -1.47749222 -0.22453742  0.29410175  0.22133922]
 [ 0.31899147  0.76238144 -0.60113103  0.13112162 -1.52117333 -0.14723033
  -0.06294454  0.34128555 -0.99916709  0.9029892 ]
 [-0.59191704 -1.04557205  0.45940653 -0.26273769 -2.34721326  2.28170719
  -1.11620077 -0.24280706 -0.80453612 -0.2854

In [7]:
x = np.array([1,2,3])
y = np.array([10,20,30])

# Fast Vectorized Ops
result = x * y
print(result)

# np.sqrt(x)
# np.exp(x)
# np.add(x,y)



[10 40 90]


### Broadcasting Rules
 `Rule: Dimensions are compatible if they are equal, or if one of them is 1`

In [8]:
A = np.ones((3,3))
B = np.array([1,2,3])
C = A + B
C

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [9]:
D = np.array([1,2,3]).reshape(3,1)
print("D:\n",D)

E = np.array([1,2,3])
F = D + E
print("\n\nF\n",F)

D:
 [[1]
 [2]
 [3]]


F
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


### Boolean Masking
 The most important tool for data cleaning and outlier detection
1. Filter Values based on condintions
2. Replace noise with specific values
3. Combine masks with bitwise operator

In [10]:
data =  np.random.randn(100)
print("data",data)

data [-1.49557797e+00 -1.86272262e+00 -1.44426364e-01 -7.97603797e-01
 -1.14942723e+00  5.38047663e-01  1.42303121e+00 -3.71583657e-01
 -1.78287680e-01  1.08230205e+00 -5.70653283e-01 -1.37778513e+00
  1.27749136e+00 -2.88891555e-01  1.39334207e+00  7.25743346e-01
 -2.80347088e-01  4.64455157e-01 -1.46977320e-01  1.43218713e+00
 -6.12862228e-01  1.38996275e+00 -3.95919450e-04  1.23133219e+00
  2.87061220e-01 -1.96960139e-01  1.29785867e+00  3.13578379e-01
  1.71488986e-01 -9.09469480e-01  1.92376989e+00 -1.38418220e+00
 -1.36060609e-01  5.10194048e-01  3.15977588e-01  1.05909418e-01
 -4.19867745e-01 -3.48457708e-01 -1.47682540e-02  4.70785121e-02
  1.38783718e-01 -1.78778866e+00  5.10321690e-01 -1.01003321e+00
  1.04840695e-01 -1.03829167e+00 -2.10670616e-01 -1.12514360e-01
 -2.10833485e+00  2.93878879e-01 -2.35157216e-01  2.77496574e-01
 -5.19531576e-01 -4.08836779e-01  3.12845749e-01 -7.27874896e-01
 -1.79582570e+00  9.45719113e-01 -4.84482965e-01 -7.81755829e-01
 -9.32688847e-01 -1.

In [11]:
mask = data > 0
print("\n mask",mask)


 mask [False False False False False  True  True False False  True False False
  True False  True  True False  True False  True False  True False  True
  True False  True  True  True False  True False False  True  True  True
 False False False  True  True False  True False  True False False False
 False  True False  True False False  True False False  True False False
 False False False False False False  True  True False  True  True  True
 False False  True  True  True  True  True False  True False  True False
 False False False  True False  True  True False False  True  True  True
 False False  True False]


In [12]:
pos_data = data[mask]
pos_data

array([0.53804766, 1.42303121, 1.08230205, 1.27749136, 1.39334207,
       0.72574335, 0.46445516, 1.43218713, 1.38996275, 1.23133219,
       0.28706122, 1.29785867, 0.31357838, 0.17148899, 1.92376989,
       0.51019405, 0.31597759, 0.10590942, 0.04707851, 0.13878372,
       0.51032169, 0.1048407 , 0.29387888, 0.27749657, 0.31284575,
       0.94571911, 0.2435864 , 1.63528003, 1.02247586, 1.05375092,
       0.33097597, 0.09898595, 1.05349825, 0.29040981, 0.33897636,
       0.40223255, 1.33189038, 1.19149329, 0.65744191, 0.73050714,
       0.18591832, 0.78005443, 0.66389872, 2.14143704, 0.42411277])

In [13]:
# Remove Outliers
data[data > 0.5] = 0.5
data

array([-1.49557797e+00, -1.86272262e+00, -1.44426364e-01, -7.97603797e-01,
       -1.14942723e+00,  5.00000000e-01,  5.00000000e-01, -3.71583657e-01,
       -1.78287680e-01,  5.00000000e-01, -5.70653283e-01, -1.37778513e+00,
        5.00000000e-01, -2.88891555e-01,  5.00000000e-01,  5.00000000e-01,
       -2.80347088e-01,  4.64455157e-01, -1.46977320e-01,  5.00000000e-01,
       -6.12862228e-01,  5.00000000e-01, -3.95919450e-04,  5.00000000e-01,
        2.87061220e-01, -1.96960139e-01,  5.00000000e-01,  3.13578379e-01,
        1.71488986e-01, -9.09469480e-01,  5.00000000e-01, -1.38418220e+00,
       -1.36060609e-01,  5.00000000e-01,  3.15977588e-01,  1.05909418e-01,
       -4.19867745e-01, -3.48457708e-01, -1.47682540e-02,  4.70785121e-02,
        1.38783718e-01, -1.78778866e+00,  5.00000000e-01, -1.01003321e+00,
        1.04840695e-01, -1.03829167e+00, -2.10670616e-01, -1.12514360e-01,
       -2.10833485e+00,  2.93878879e-01, -2.35157216e-01,  2.77496574e-01,
       -5.19531576e-01, -

In [14]:
data[data < -0.5] = 0.5
data

array([ 5.00000000e-01,  5.00000000e-01, -1.44426364e-01,  5.00000000e-01,
        5.00000000e-01,  5.00000000e-01,  5.00000000e-01, -3.71583657e-01,
       -1.78287680e-01,  5.00000000e-01,  5.00000000e-01,  5.00000000e-01,
        5.00000000e-01, -2.88891555e-01,  5.00000000e-01,  5.00000000e-01,
       -2.80347088e-01,  4.64455157e-01, -1.46977320e-01,  5.00000000e-01,
        5.00000000e-01,  5.00000000e-01, -3.95919450e-04,  5.00000000e-01,
        2.87061220e-01, -1.96960139e-01,  5.00000000e-01,  3.13578379e-01,
        1.71488986e-01,  5.00000000e-01,  5.00000000e-01,  5.00000000e-01,
       -1.36060609e-01,  5.00000000e-01,  3.15977588e-01,  1.05909418e-01,
       -4.19867745e-01, -3.48457708e-01, -1.47682540e-02,  4.70785121e-02,
        1.38783718e-01,  5.00000000e-01,  5.00000000e-01,  5.00000000e-01,
        1.04840695e-01,  5.00000000e-01, -2.10670616e-01, -1.12514360e-01,
        5.00000000e-01,  2.93878879e-01, -2.35157216e-01,  2.77496574e-01,
        5.00000000e-01, -

In [15]:
# Advanced array shape shifing
arr = np.array([1,2,3,4,5])

# 1. Reshape
print("reshape\n",arr.reshape(5,1))

# 2. Transpose
print("\ntranspose",arr.T)

# 3. Concatenate: Stacking datasets vertically or horizontally
print("\nv_stack\n",np.vstack((1,2,3)))

reshape
 [[1]
 [2]
 [3]
 [4]
 [5]]

transpose [1 2 3 4 5]

v_stack
 [[1]
 [2]
 [3]]


In [16]:
# Lab: Matrix Algebra

A = np.array([[1,2],[3,4]])
B = np.linalg.inv(A)
print("B\n", B)

I = A @ B
print("\nMatrix Mult: (I = A @ B) \n", I)

eig_vals = np.linalg.eigvals(A)
print("\nEigen Values:\n",eig_vals)

B
 [[-2.   1. ]
 [ 1.5 -0.5]]

Matrix Mult: (I = A @ B) 
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Eigen Values:
 [-0.37228132+0.j  5.37228132+0.j]
